<?php

/*
 * kardesyazilim.net
 * leo@kardesyazilim
 * 20.Tem.2013-12:55:04 
 * db
 */





define('MDBTYPE',$mdbType);
define('MDBPORT',$mdbPort);
define('MDBSRV',$mdbSRV);
define('MDBUSR',$mdbUSR);
define('MDBPASS',$mdbPASS);
define('MDBNAME',$mdbNAME);
define('MDBC',$mdbC);
define('MDBCSIZE',$mdbCSIZE);
define('MDBCTIME',$mdbCTIME);
define('MDBENC',$mdbENC);

define('SDBTYPE',$sdbType);
define('SDBPORT',$sdbPort);
define('SDBSRV',$sdbSRV);
define('SDBUSR',$sdbUSR);
define('SDBPASS',$sdbPASS);
define('SDBNAME',$sdbNAME);
define('SDBC',$sdbC);
define('SDBCSIZE',$sdbCSIZE);
define('SDBCTIME',$sdbCTIME);






?>
